apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-python
  labels:
    app: k8s-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-python
  template:
    metadata:
      labels:
        app: k8s-python
    spec:
      containers:
      - name: k8s-python
        image: 090011926616.dkr.ecr.us-east-1.amazonaws.com/demo_eks_python_webserver:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100M
        ports:
        - containerPort: 8081



